DROP TABLE IF EXISTS Personne;
DROP TABLE IF EXISTS Adresse;

create table Personne (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    version integer not null,
    nom_naissance varchar(30) not null,
    nom_usage varchar(30) not null,
    prenom varchar(30) not null,
    dt_naissance timestamp  not null,
    dt_deces timestamp,
    genre varchar(30) not null
);

insert into Personne (version,nom_naissance,nom_usage,prenom,dt_naissance,dt_deces,genre) values
(0,'Dupond','Dupond','Louis',DATE '1913-03-12', null,'Homme');

insert into Personne (version,nom_naissance,nom_usage,prenom,dt_naissance,dt_deces,genre) values
(0,'Jenkins','Jenkins','Jhon',DATE '1973-06-11', null,'Homme');

create table Adresse (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    Ligne1 varchar(30) ,
    Ligne2 varchar(30) ,
    Ligne3 varchar(30) ,
    Ligne4 varchar(30) ,
    Ligne5 varchar(30) ,
    Ligne6 varchar(30)
);

insert into Adresse (Ligne1,Ligne2,Ligne3,Ligne4,Ligne5,Ligne6) values
  ('Ligne01','Ligne02','Ligne03','Ligne04','Ligne05','Ligne06');
insert into Adresse (Ligne1,Ligne2,Ligne3,Ligne4,Ligne5,Ligne6) values
  ('Ligne11','Ligne12','Ligne13','Ligne14','Ligne15','Ligne16');

create table Personne_Adresse (
  Personne_id bigint foreign key references Personne (ID) ,
  Adresse_id bigint foreign key references Adresse (ID)
);

insert into Personne_Adresse (Personne_id,Adresse_id) values (0,0);
insert into Personne_Adresse (Personne_id,Adresse_id) values (0,1);